FROM ubuntu:20.04

LABEL maintainer="TienDang <tiendang.memo@gmail.com>"

RUN set -eux \
    && apt-get update \
    && apt-get install -y software-properties-common \
    && add-apt-repository -y ppa:ondrej/php \
    #
    #--------------------------------------------------------------------------
    # Software's Installation
    #--------------------------------------------------------------------------
    #
    && echo 'DPkg::options { "--force-confdef"; };' >> /etc/apt/apt.conf \
    # Install "PHP Extentions", "libraries", "Software's"
    && apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y --allow-downgrades --allow-remove-essential \
        --allow-change-held-packages \
        php8.0-cli \
        php8.0-common \
        php8.0-curl \
        php8.0-intl \
        php8.0-xml \
        php8.0-mbstring \
        php8.0-mysql \
        php8.0-pgsql \
        php8.0-sqlite \
        php8.0-sqlite3 \
        php8.0-zip \
        php8.0-bcmath \
        php8.0-gd \
        php8.0-dev \
        php-memcached \
        pkg-config \
        libwebp-dev \
        libcurl4-openssl-dev \
        libedit-dev \
        libssl-dev \
        libxml2-dev \
        xz-utils \
        libsqlite3-dev \
        postgresql-client \
        rsync \
        sqlite3 \
        gcc \
        git \
        curl \
        wget \
        vim \
        tree \
        yasm \
    && apt-get clean \
    #####################################
    # Composer:
    #####################################
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


# always run apt update when start and after add new source list, then clean up at end.
RUN apt-get update -yqq && \
	apt-get install -yqq \
		apt-utils \
		libzip-dev \
		zip \
		unzip

# Clean up
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/* && \
    rm /var/log/lastlog /var/log/faillog