name: Docker Image CI

on:
    push:
        branches: '**'
        tags: '**'
    pull_request:
        branches: [ master ]

jobs:
    
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php_version: [ "7.3", "7.4" ,"8.0" ]
        steps:
            -   name: Check Out Repo
                uses: actions/checkout@v2
                
            -   name: Docker meta
                id: meta
                uses: crazy-max/ghaction-docker-meta@v2
                with:
                    images:
                        ${{ secrets.DOCKER_HUB_USERNAME }}/madolche-workplace
                    flavor: |
                        suffix=-v${{ matrix.php_version }}
                    tags: |
                        type=ref,event=tag
                        type=ref,event=branch
                        type=semver,pattern={{version}}
                        type=raw,value=latest

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v1
            
            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            
            -   name: Login to Docker Hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_PASSWORD }}
                    
            -   name: Build and push
                uses: docker/build-push-action@v2
                with:
                    file: Dockerfile-${{ matrix.php_version }}
                    push: true
                    platforms: linux/amd64,linux/arm64
                    tags: ${{ steps.meta.outputs.tags }}
